server:
  port: 8888
  http2:
    enabled: true
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  prometheus.metrics.export.enabled: true
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MilczekT1/config-git
          default-label: master
          search-paths:
            - 'account-management'
            - 'budget-management'
            - 'family-management'
            - 'mail'
            - 'password-management'
            - 'mvc'
  main:
    allow-bean-definition-overriding: true
budget:
  chassis:
    http-logging:
      enabled: true
